project:
  type: website

brand: tlm-styles/_brand.yml

resources:
  - "**/*.pdf"

website:
  title: "BIOL 275 Biostatistics"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: syllabus/index.qmd
        text: Syllabus
      - href: schedule/index.qmd
        text: Schedule
      - href: lectures/index.qmd
        text: Lectures
      - href: labs/index.qmd
        text: Labs
      - href: project/index.qmd
        text: Project
  sidebar:
    style: "docked"
    search: true
    contents: 
      - href: index.qmd
        text: Home
      - href: syllabus/index.qmd
      - href: schedule/index.qmd
      - href: lectures/index.qmd
      - section: "Labs"
        contents:
          - labs/index.qmd
          - labs/introduction-to-r-and-rstudio/index.qmd
          - labs/workflow-and-data-types/index.qmd
          - labs/importing-data/index.qmd
          - labs/graphing-ggplot/index.qmd
          - labs/ggplot2-vis-challenge/index.qmd
          - labs/describing-data/index.qmd
      - section: "Project"
        contents:
          - project/index.qmd
          - project/datasets.qmd
          - project/dryad-datasets.qmd
          - project/team-formation.qmd
          - project/data-readiness-check.qmd
format:
  html:
    toc: true
    toc-depth: 2
    number-sections: false
    code-link: true
    theme: 
      - default
      - styles.scss
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://use.typekit.net/tag1lvz.css">

execute:
  echo: false
  warning: false
  message: false