project:
  type: website
  output-dir: _site

resources:
  - "**/*.pdf"

website:
  title: "BIOL 275 Biostatistics"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: syllabus/index.qmd
        text: Syllabus
      - href: schedule/index.qmd
        text: Schedule
      - href: lectures/index.qmd
        text: Lectures
      - href: labs/index.qmd
        text: Labs
  sidebar:
    style: "docked"
    search: true
    contents: 
      - href: index.qmd
        text: Home
      - href: syllabus/index.qmd
      - href: schedule/index.qmd
      - href: lectures/index.qmd
      - href: labs/index.qmd
        
format:
  html:
    toc: true
    theme: default
    css: tlm-styles/styles.scss

execute:
  echo: false
  warning: false
  message: false